In [2]:
import numpy as np

1 . Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.


In [3]:
lst = [1,2,3,4,5]
np_array = np.array(lst)
print(np_array)

[1 2 3 4 5]


2.Create a 3x3 matrix with values ranging from 2 to 10.


In [4]:
arr = np.arange(2,11)
arr_2d = arr.reshape(3,3)
print(arr_2d)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [5]:
arr = np.zeros(11)
print(arr)
arr[5] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last)

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
rev_arr = arr[::-1]
print(rev_arr)

[1 2 3 4 5]
[5 4 3 2 1]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


In [7]:
arr_2d = np.ones((5,5))
print(arr_2d)
arr_2d[1:-1, 1:-1] = 0
print('\n',arr_2d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [8]:
arr = np.ones((3,3))
print(arr)
border = np.zeros((5,5))
border[1:-1,1:-1] = arr
print('\n',border)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [9]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [10]:
lst = [1,2,3,4,5,6,7,8]
arr_lst = np.array(lst)
print(arr_lst)
tup = ((8,4,6),(1,2,3))
arr_tup = np.array(tup)
print(arr_tup)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


9.  Write a Python program to append values to the end of an array.

In [11]:
arr = np.array([10,20,30])
print(arr)
arr = np.append(arr,[40,50,60,70,80,90])
print(arr)

[10 20 30]
[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [12]:
arr = np.array([1.00000000+0.j,0.70710678+0.70710678j])
real_arr = np.real(arr)
imag_arr = np.imag(arr)
print(f'Real part of array :{real_arr}\nImaginary part of array:{imag_arr}')

Real part of array :[1.         0.70710678]
Imaginary part of array:[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the element

In [13]:
arr = np.array([1,2,3])
print(f'Number of elements in array{arr.size}, length of one array element in bytes is {arr.itemsize} and total bytes consumed by the element is {arr.nbytes}')

Number of elements in array3, length of one array element in bytes is 8 and total bytes consumed by the element is 24


12. Write a Python program to find common values between two arrays

In [14]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8])
common = np.intersect1d(arr1,arr2)
print(common)

[5]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [15]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
set_diff = np.setdiff1d(arr1,arr2)
print(set_diff)

[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [16]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
set_excl = np.setxor1d(arr1,arr2)
print(set_excl)

[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.


In [17]:
a = np.array([1,2])
b = np.array([4,5])

print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


15. Save numpy array to text file.

In [18]:
arr = np.zeros((3,3))
path = 'D:/numpy.txt'
np.savetxt(path,arr,delimiter=',',fmt = '%.2f')

16. Write a Python program to create a contiguous flattened array
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]


In [19]:
arr = np.array([[10,20,30],[20,40,50]])
print(arr)
arr = np.ravel(arr)
print(arr)

[[10 20 30]
 [20 40 50]]
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.


In [20]:
arr = np.array([[2,4,6],[6,8,10]], dtype = np.int32)
print(arr)
print(f'Data type of the array is {arr.dtype}')
arr_new = arr.astype(np.float64)
print(f"New Type: {arr_new.dtype}")
print(arr_new)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array is int32
New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [21]:
arr = np.zeros((3,3))
print(arr)
for i in range(len(arr)):   
 arr[i,i] =1
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [22]:
arr = np.zeros((4,3))
for i in range(1,len(arr)):
    arr[i,:i]=1
print(arr)


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays

In [23]:
arr1 = np.array([[0,1,3],[5,7,9]])
arr2 = np.array([[0, 2, 4],[6, 8, 10]])
new_arr = np.concatenate((arr1,arr2),axis=1)
print(new_arr)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).


Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr.setflags(write=False)
print('Test the array is read only or not:')
try:
    arr[1,2] = 9
except ValueError as e:
    print(e)

[[1 2 3]
 [4 5 6]]
Test the array is read only or not:
assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.


In [25]:
arr = np.arange(12).reshape(3,4)
print(arr)
arr = arr[:]*3
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [26]:
arr = np.arange(0,6).reshape(3,2)
print('orginal elements\n',arr)
lst = arr.tolist()
print('new array\n',lst)

orginal elements
 [[0 1]
 [2 3]
 [4 5]]
new array
 [[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.


In [27]:
arr = ([ 0.26153123 ,0.52760141 ,0.5718299, 0.5927067, 0.7831874 ,0.69746349,0.35399976 ,0.99469633, 0.0694458 ,0.54711478])
print('original array\n',arr)
print('array values with precision 3\n',np.round(arr,decimals=3))

original array
 [0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478]
array values with precision 3
 [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array

In [28]:
arr = np.array([ 1.60000000e-10 ,1.60000000e+00 ,1.20000000e+03 ,2.35000000e-01])
print('original array\n',np.array2string(arr, precision=8, suppress_small=False))

np.set_printoptions(suppress=True, precision=3)
print('array values with precision 3\n',arr)

original array
 [1.60e-10 1.60e+00 1.20e+03 2.35e-01]
array values with precision 3
 [   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.


In [29]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr)
new = np.array([[100],[200]])
arr = np.hstack((arr,new))
print(arr)

[[10 20 30]
 [40 50 60]]
[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array

In [30]:
arr = np.arange(10,110,10)
print('Orignial array: ',arr)
indices = [0,3,4]
arr = np.delete(arr,indices)
print('Array after deleting first,fourth and fifth element:',arr)



Orignial array:  [ 10  20  30  40  50  60  70  80  90 100]
Array after deleting first,fourth and fifth element: [ 20  30  60  70  80  90 100]
