In [1]:
import numpy as np

1 . Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.


In [2]:
lst = [1,2,3,4,5]
np_array = np.array(lst)
print(np_array)

[1 2 3 4 5]


2.Create a 3x3 matrix with values ranging from 2 to 10.


In [4]:
arr = np.arange(2,11)
arr_2d = arr.reshape(3,3)
print(arr_2d)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [8]:
arr = np.zeros(11)
print(arr)
arr[5] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last)

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)
rev_arr = arr[::-1]
print(rev_arr)

[1 2 3 4 5]
[5 4 3 2 1]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


In [17]:
arr_2d = np.ones((5,5))
print(arr_2d)
arr_2d[1:-1, 1:-1] = 0
print('\n',arr_2d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [19]:
arr = np.ones((3,3))
print(arr)
border = np.zeros((5,5))
border[1:-1,1:-1] = arr
print('\n',border)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [21]:
arr = np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [ ]:
lst = [1,2,3,4,5]
arr_lst = np.array(lst)
