Pandas Problems:

In [1]:
import pandas as pd
import numpy as np

1. Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module

In [3]:
series = pd.Series([1,2,3,4,5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


2. Write a Python program to convert a Panda module Series to Python list and it's type

In [5]:
series = pd.Series([1,2,3,4,5])
arr = series.to_numpy()
print(f'{arr}\n{type(arr)}')

[1 2 3 4 5]
<class 'numpy.ndarray'>


3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [9]:
series1 = pd.Series([2,4,6,8,10])
series2 = pd.Series([1,3,5,7,9])
print('Addition:\n',series1 + series2)
print('Subtract:\n',series1-series2)
print('Multiple\n',series1*series2)
print('Divide\n',series1/series2)

Addition:
 0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract:
 0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiple
 0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Python program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]


In [32]:
series1 = pd.Series([0,1,2,3,4,5,6])
series2 = pd.Series([3,3,3,3,3,3,3])
print(series1 ** series2)

0      0
1      1
2      8
3     27
4     64
5    125
6    216
dtype: int64


5. Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels

In [19]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)
print(df)

        name  score  attempts qualify labels
0  Anastasia   12.5         1     yes      a
1       Dima    9.0         3      no      b
2  Katherine   16.5         2     yes      c
3      James    NaN         3      no      d
4      Emily    9.0         2      no      e
5    Michael   20.0         3     yes      f
6    Matthew   14.5         1     yes      g
7      Laura    NaN         1      no      h
8      Kevin    8.0         2      no      i
9      Jonas   19.0         1     yes      j


6. Write a Python program to display a summary of the basic information about a
specified Data Frame and its data.

In [21]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
 4   labels    10 non-null     object 
dtypes: float64(1), int64(1), object(3)
memory usage: 532.0+ bytes
None


7. Write a Python program to get the first 3 rows of a given DataFrame

In [22]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df.head(3))

        name  score  attempts qualify labels
0  Anastasia   12.5         1     yes      a
1       Dima    9.0         3      no      b
2  Katherine   16.5         2     yes      c


8. Write a Python program to select the 'name' and 'score' columns from the following
DataFrame.


In [23]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df[['name', 'score']])

        name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5
3      James    NaN
4      Emily    9.0
5    Michael   20.0
6    Matthew   14.5
7      Laura    NaN
8      Kevin    8.0
9      Jonas   19.0


9. Write a Python program to select the specified columns and rows from a given data
frame

In [36]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df.loc[[1,3,5,6],['name','score']])

      name  score
1     Dima    9.0
3    James    NaN
5  Michael   20.0
6  Matthew   14.5


10. Write a Python program to select the rows where the number of attempts in the
examination is greater than 2

In [38]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df[df['attempts']>2])

      name  score  attempts qualify labels
1     Dima    9.0         3      no      b
3    James    NaN         3      no      d
5  Michael   20.0         3     yes      f


11. Write a Python program to count the number of rows and columns of a DataFrame.


In [39]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df.shape)

(10, 5)


12. Write a Python program to select the rows where the score is missing, i.e. is NaN

In [49]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df[df['score'].isna()])

    name  score  attempts qualify labels
3  James    NaN         3      no      d
7  Laura    NaN         1      no      h


13. Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15.


In [ ]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)

print(df[(df['attempts']< 2 )&(df['score'] > 15)])

    name  score  attempts qualify labels
9  Jonas   19.0         1     yes      j


14. Write a Python program to change the score in row 'd' to 11.5.


In [70]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)
print(df)
df.loc[df['labels']=='d','score'] = 11.5
print(f'After editing :\n{df}')


        name  score  attempts qualify labels
0  Anastasia   12.5         1     yes      a
1       Dima    9.0         3      no      b
2  Katherine   16.5         2     yes      c
3      James    NaN         3      no      d
4      Emily    9.0         2      no      e
5    Michael   20.0         3     yes      f
6    Matthew   14.5         1     yes      g
7      Laura    NaN         1      no      h
8      Kevin    8.0         2      no      i
9      Jonas   19.0         1     yes      j
After editing :
        name  score  attempts qualify labels
0  Anastasia   12.5         1     yes      a
1       Dima    9.0         3      no      b
2  Katherine   16.5         2     yes      c
3      James   11.5         3      no      d
4      Emily    9.0         2      no      e
5    Michael   20.0         3     yes      f
6    Matthew   14.5         1     yes      g
7      Laura    NaN         1      no      h
8      Kevin    8.0         2      no      i
9      Jonas   19.0         1     yes  

15. Write a Python program to calculate the sum of the examination attempts by the
students.

In [74]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)
print('Sum of attempts:',df['attempts'].sum())

Sum of attempts: 19


16. Write a Python program to calculate the mean score for each different student in
DataFrame.


In [76]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)
print('Mean score for students\n',df.groupby('name')['score'].mean())

Mean score for students
 name
Anastasia    12.5
Dima          9.0
Emily         9.0
James         NaN
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Name: score, dtype: float64


17. Write a Python program to append a new row 'k' to data frame with given values for
each column. Now delete the new row and return the original DataFrame

In [ ]:
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael','Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'labels' : ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

df= pd.DataFrame(exam_data)
